version: "3.9"
volumes:
  db-store:
  psysh-store:
  pgadmin4_volume:
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    ports:
      - "2222:22"
    volumes:
      - type: bind
        source: ./src
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - APP_NAME=${APP_NAME}
      - APP_DEBUG=${APP_DEBUG}
      - APP_ENV=${APP_ENV}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /workspace

  db:
    build:
      context: .
      dockerfile: ./infra/docker/postgres/Dockerfile
    ports:
      - target: 5432
        published: ${DB_PUBLISHED_PORT:-5432}
        protocol: tcp
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_DB=${DB_DATABASE:-FoodJournal}
      - POSTGRES_USER=${DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_HOST=${DB_HOST:-db}
      - POSTGRES_CONFIG_FILE=${POSTGRES_CONFIG_FILE:-/etc/postgresql/postgresql.conf}
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:6.5
    ports:
      - "8080:80"
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    depends_on:
      - db
    restart: always

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
