CREATE USER "${POSTGRES_USER}" WITH PASSWORD '${POSTGRES_PASSWORD}';
ALTER USER "${POSTGRES_USER}" CREATEDB;

-- 新しく作成されるデータベースに対して権限を付与する
ALTER USER "${POSTGRES_USER}" WITH CREATEDB;

-- 新しく作成されるスキーマに対して権限を付与する
ALTER USER "${POSTGRES_USER}" WITH CREATE;

-- デフォルトの public スキーマでの操作権限を付与する
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, REFERENCES, TRIGGER, EXECUTE ON SCHEMA public TO "${POSTGRES_USER}";

-- 既存のデータベースの public スキーマでの操作権限を付与する
-- ここで、'your_database_name' を対象のデータベース名に置き換えてください
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, REFERENCES, TRIGGER, EXECUTE ON ALL SEQUENCES IN SCHEMA public TO "${POSTGRES_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO "${POSTGRES_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, REFERENCES, TRIGGER, EXECUTE ON SEQUENCES TO "${POSTGRES_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "${POSTGRES_USER}";
